gettext("Administration Student")
gettext("'Steel with steel is bad...'|(Zamboy, future Administration Student)")
gettext("Also known as Taylor's little boys, Administration Students are frequently found in front of self-help shelves in commercial bookstores. They have chosen their course of studies because they do not really know what they want to do with their lives (exact sciences, human sciences, group dynamics?) and, although in most cases they have NOTHING to administer, they firmly believe that what they are doing is useful to others and to themselves.")
d4
6
-2 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("Administration students are very definitely not known for their intellectual capacities. (Am I wrong, Elis Regina?). So, they receive -2 of Intelligence.")
-4 ATTRIBUTE CHARISMA ALL ALL
gettext("It's a real turn-off to find some of those dumb asses in a group. -4 of Charisma.")
2 ATTRIBUTE CONSTITUTION ALL ALL
gettext("The works of Taylor are a common part of the Administration Students' course of study. +2 for Constitution.")
4 SKILL BOVINICE ALL ALL
gettext("Since they are Taylor's faithful disciples, they receive +4 of Taylorism Skill.")
4 SKILL BIZARRE_CLOTHES ALL ALL
gettext("In their dogmatic cult to Taylor they found bizarre things (with maximun financial efficiency) to be their 'clothes', receiving +4 of Bizarre Clothes.")
-6 SKILL LISTEN ALL ALL 
gettext("Everyone knows that Administration Students have a lot of difficulty in the assimilation of other's opinions, and also to ask in a concise way some question, so they receive -6 of Listen.")
8
1 ESTHETIC_SHOCK_I
3 STUN_ATTACK
5 ESTHETIC_SHOCK_II
7 IMPROVED_STUN_ATTACK
10 WEB_DESIGN
15 ESTHETIC_SHOCK_III
20 SUPREME_ESTHETIC_SHOCK
20 ABERRATION
7
APPRAISE
BIZARRE_CLOTHES
BRIBE
BURGLARIZE
COUNTERFEIT
FOOT_ON_MANS_GENITALS
PROFESSIONAL_SPEECH
( 2 - INTELLIGENCE )x3
( 2 - INTELLIGENCE )x1
1,0/0/0/0/0/0,0/2/2
2,1/0/0/0/0/0,1/3/3
3,1/0/0/0/0/0,1/3/3
4,2/0/0/0/0/0,2/4/4
5,2/0/0/0/0/0,2/4/4
6,3/0/0/0/0/0,3/5/5
7,3/0/0/0/0/0,3/5/5
8,4/0/0/0/0/0,4/6/6
9,4/0/0/0/0/0,4/6/6
10,5/0/0/0/0/0,5/7/7
11,5/0/0/0/0/0,5/7/7
12,6/1/0/0/0/0,6/8/8
13,6/1/0/0/0/0,6/8/8
14,7/2/0/0/0/0,7/9/9
15,7/2/0/0/0/0,7/9/9
16,8/3/0/0/0/0,8/10/10
17,8/3/0/0/0/0,8/10/10
18,9/4/0/0/0/0,9/11/11
19,9/4/0/0/0/0,9/11/11
20,15/10/5/0/0/0,16/6/7
