gettext("Biology Student")
gettext("'This place is filled with arthropodes!'|(Bin, that time, a Biology Student)")
gettext("Able to be for two weeks isoleted in the mountains doing their 'Field Works', ambushing and observing the incredible and exciting ameiva's feed habits (and sometimes mistaken as Hippies in their search for Feed-Karma), the Biology Students are from all things a few: a few  medicians, a few hippies,  a few computers, a few hot-dog sellers...")
d8
5
2 ATT DEXTERITY ALL ALL
gettext("+2 of Dexterity, since they always observe and follow in distinct terrains the ameivas (and by also open its body, counting how many worms it has).")
-1 ATT STRENGTH ALL ALL
gettext("-1 of Strength, since their muscles atrophy after spent 12 hours inert observing the ameiva's coupling rituals.")
6 SKILL DISGUISES CLASS HIPPIE
gettext("Since they are commonly mistaken as hippies, Biology Students receive +6 of Disguises when disguised as hippie (and when not of this race)")
-4 SKILL FREE_PASS ALL ALL
gettext("For the same reason, -4 of free-pass.")
2 SKILL FURTIVE ALL ALL
gettext("For the hard work observing ameivas, the Biology Student receveis +2 of furtivity.")
7
1 AMEIVAS_ADORATION
4 AMEIVAS_WORMS
7 ARC_IMPULSE
10 MASS_ATHROPODS_ATTACK
15 DARWIN
18 STRANGLERS_ENTES
20 PLEINE_COMMANDE_DE_NATURE
11
DISGUISES
FURTIVE
HIDE
KNOWLEDGE(BIOLOGY)
LISTEN
MEDICAL_LOUD_MOUTH
OBSERVATE
OUT_OF_TIME
PROFESSIONAL_SPEECH
SCALE
TRAIN_ANIMALS
( 5 + INTELLIGENCE )x3
( 2 + INTELLIGENCE )x1
1,0/0/0/0/0/0,1/2/1
2,1/0/0/0/0/0,2/3/2
3,1/0/0/0/0/0,2/4/3
4,2/0/0/0/0/0,4/5/4
5,2/0/0/0/0/0,4/6/5
6,3/0/0/0/0/0,5/7/6
7,3/0/0/0/0/0,5/7/6
8,4/0/0/0/0/0,6/8/7
9,4/0/0/0/0/0,7/9/8
10,5/0/0/0/0/0,7/10/8
11,5/0/0/0/0/0,8/11/9
12,6/1/0/0/0/0,8/11/9
13,6/1/0/0/0/0,9/12/10
14,7/2/0/0/0/0,10/13/11
15,7/2/0/0/0/0,11/14/12
16,8/3/0/0/0/0,12/15/13
17,8/3/0/0/0/0,13/16/14
18,9/4/0/0/0/0,14/17/15
19,9/4/0/0/0/0,14/17/15
20,13/8/3/0/0/0,15/18/16
