gettext("Biology Student")
gettext("'This place is filled with arthropodes!'|(Bin, that time, a Biology Student)")
gettext("Able to be isolated in the mountains for two weeks at a time doing their 'Field Work', ambushing and observing the incredible and exciting ameiva's feeding habits (and they are sometimes mistaken as Hippies in their search for Feed-Karma), the Biology Students can be all things to all men: among them, there are a few doctors, a few hippies, a few computer analysts, a few hot-dog sellers...")
d8
5
2 ATTRIBUTE DEXTERITY ALL ALL
gettext("+2 of Dexterity, since they always observe and follow the ameivas on whatever terrain (and also dissect them, to count how many worms they have).")
-1 ATTRIBUTE STRENGTH ALL ALL
gettext("-1 of Strength, cause their muscles atrophy after spending 12 hours motionless, observing the ameiva's coupling rituals. ")
6 SKILL DISGUISES CLASS HIPPIE
gettext("Since they are commonly mistaken for hippies, Biology Students receive +6 of Disguises when disguised as hippies (and when not of this race)")
-4 SKILL FREE_PASS ALL ALL
gettext("For the same reason, -4 of Carte Blanche.")
2 SKILL FURTIVE ALL ALL
gettext("For the hard work observing ameivas, the Biology Student receives +2 of furtivity.")
7
1 AMEIVAS_ADORATION
4 AMEIVAS_WORMS
7 ARC_IMPULSE
10 MASS_ATHROPODS_ATTACK
15 DARWIN
18 STRANGLERS_ENTES
20 PLEINE_COMMANDE_DE_NATURE
11
CLIMB
DISGUISES
FURTIVE
HIDE
KNOWLEDGE_GENERAL
LISTEN
MEDICAL_LOUD_MOUTH
OBSERVATE
OUT_OF_TIME
PROFESSIONAL_SPEECH
TRAIN_ANIMALS
( 5 + INTELLIGENCE )x3
( 2 + INTELLIGENCE )x1
1,0,1/2/1
2,1,2/3/2
3,1,2/4/3
4,2,4/5/4
5,2,4/6/5
6,3,5/7/6
7,3,5/7/6
8,4,6/8/7
9,4,7/9/8
10,5,7/10/8
11,5,8/11/9
12,6,8/11/9
13,6,9/12/10
14,7,10/13/11
15,7,11/14/12
16,8,12/15/13
17,8,13/16/14
18,9,14/17/15
19,9,14/17/15
20,13,15/18/16
