gettext("Computer Science Student")
gettext("'I really don't know why I want to earn this diploma...|Are you stupid? For the women, obviously!'|(Gushm, then a CS Student, answering the existential question of his class).")
gettext("The Computer Science Student is the most bizarre class in DccNiTghtmare (and, paradoxically, the most common). They are known by their suicidal choices (the first one being the course of studies they have chosen), their lack of patience when attending what their masters call 'classes', the infinite time spent on Practical Exercises (TPs) and the hatred they feel when they perceive that what they have done works perfectly, but their masters won't look at and appraise it, since CS teachers are disciplined and will not compromise the worth of the diploma.")
d8
4
2 ATTRIBUTE WISDOM ALL ALL
gettext("Because they have to teach themselves, they receive +2 of Wisdom.")
-1 ATTRIBUTE CHARISMA ALL ALL
gettext("By their natural tendency to be qualified as Geeks, being one or not, they receive -1 of Charisma.")
5 SAVE FORTITUDE ALL ALL
gettext("Computer Science Students receive +5 of fortitude for surviving their boring studies that are just a pale imitation of what real computer studies should be.")
-2 SAVE REFLEX ALL ALL
gettext("Also receive -2 of reflexes for the mount of time spent in front of a computer.")
11
1 SUICIDAL_CHOICES
2 SUFFER_RESISTANCE
3 DESTROY_PROPRIETARY_SOFTWARE_ADEPTS
3 DESTROY_FREE_SOFTWARE_ADEPTS
5 I_KNOW_AND_YOU_DONT
9 WORLD_CONCEPTION
9 CYBERNETIC_BODY
10 OC2_TRAUMA
12 IMPROVED_SUFFER_REISTENCE
15 PARALEL_REALITY
20 CHAOS_MATRIX
10
DRINKING
BLUFF
KNOWLEDGE(TECNOLOGY)
KNOWLEDGE(SUFFER)
PROFESSIONAL_SPEECH
HIDE
LISTEN
OPERATE_ELETRONIC_OBJECTS
PRESTIDIGITATION
OUT_OF_TIME
( 4 + INTELLIGENCE )x3
( 4 + INTELLIGENCE )x1
1,1/0/0/0/0/0,2/0/1
2,1/0/0/0/0/0,3/1/2
3,2/0/0/0/0/0,4/2/3
4,3/0/0/0/0/0,5/3/4
5,4/0/0/0/0/0,6/4/5
6,5/0/0/0/0/0,7/5/6
7,5/0/0/0/0/0,7/5/6
8,6/1/0/0/0/0,8/6/7
9,7/2/0/0/0/0,9/7/8
10,8/3/0/0/0/0,10/7/8
11,9/4/0/0/0/0,11/8/9
12,9/4/1/0/0/0,11/8/9
13,10/5/0/0/0/0,12/9/10
14,11/6/1/0/0/0,13/10/11
15,12/7/2/0/0/0,14/11/12
16,13/8/3/0/0/0,15/12/13
17,14/9/4/0/0/0,16/13/14
18,15/10/5/0/0/0,17/14/15
19,15/10/5/0/0/0,17/14/15
20,16/11/6/1/0/0,18/15/16
