gettext("Computer Science Student")
gettext("'-I really don't know why I'm making this graduation...|- How  not? For the womans, obviously!'|(Gushm, that time CS Student, answering the CS dilema)")
gettext("Computer Science Student is the most bizarre class in DccNiTghtmare (and, paradoxically, the most common). They are knowledge by their suicidal choices (the first one is the graduation they choosed), their little patience to view what their masters call 'classes', the infinity time spent on Pratical Exercises (TPs) and the hate when they percept that it works perfectly, but their masters won't  look  and  appraise  it, since CS teachers are displicents and without any compromise with the graduation.")
d8
4
2 ATT WISDOM ALL ALL
gettext("Since they have to be self-teachers, they receive +2 of Wisdom.")
-1 ATT CHARISM ALL ALL
gettext("By their natural tendency to be qualified as Geeks, being one or not, they receive -1 of Charism.")
5 SAVE FORTITUDE ALL ALL
gettext("Computer Science Students receive +5 of fortitute by survive to their hoax and boring graduation.")
-2 SAVE REFLEX ALL ALL
gettext("Also receive -2 of reflexes for the lot of time spent in front of a computer.")
11
1 SUICIDAL_CHOICES
2 SUFFER_RESISTANCE
3 DESTROY_PROPRIETARY_SOFTWARE_ADEPTS
3 DESTROY_FREE_SOFTWARE_ADEPTS
5 I_KNOW_AND_YOU_DONT
9 WORLD_CONCEPTION
9 CYBERNETIC_BODY
10 OC2_TRAUMA
12 IMPROVED_SUFFER_REISTENCE
15 PARALEL_REALITY
20 CHAOS_MATRIX
10
DRINKING
BLUFF
KNOWLEDGE(TECNOLOGY)
KNOWLEDGE(SUFFER)
PROFESSIONAL_SPEECH
HIDE
LISTEN
OPERATE_ELETRONIC_OBJECTS
PRESTIDIGITATION
OUT_OF_TIME
( 4 + INTELLIGENCE )x3
( 4 + INTELLIGENCE )x1
1,1/0/0/0/0/0,2/0/1
2,1/0/0/0/0/0,3/1/2
3,2/0/0/0/0/0,4/2/3
4,3/0/0/0/0/0,5/3/4
5,4/0/0/0/0/0,6/4/5
6,5/0/0/0/0/0,7/5/6
7,5/0/0/0/0/0,7/5/6
8,6/1/0/0/0/0,8/6/7
9,7/2/0/0/0/0,9/7/8
10,8/3/0/0/0/0,10/7/8
11,9/4/0/0/0/0,11/8/9
12,9/4/1/0/0/0,11/8/9
13,10/5/0/0/0/0,12/9/10
14,11/6/1/0/0/0,13/10/11
15,12/7/2/0/0/0,14/11/12
16,13/8/3/0/0/0,15/12/13
17,14/9/4/0/0/0,16/13/14
18,15/10/5/0/0/0,17/14/15
19,15/10/5/0/0/0,17/14/15
20,16/11/6/1/0/0,18/15/16
