gettext("Journalism Student")
gettext("'The judge thinks he is God, the Medic plays God. The journalist, if he isn't God, convinces you that he is'|(Matheus de Paula, ex-Journalism student)")
gettext("Graduating in the arts of deceit a cheating, the journalism student is a writing master. With words, he can create events, stun his enemies, swindle his audience, towards other habilities. Despite of being college friends, these malicious creatures can be very rude to each other, not being common to see them on large groups. But they can easily join the masses, to gather as much information as possible.")
d6
6
-2 ATT STRENGTH ALL ALL
gettext("As they usually are deep involved on mental work, these organisms don't find time or will to exercise their muscles, receiving -2 of Strength.")
2 ATT INTELLIGENCE ALL ALL
gettext("Journalism students have a 'know it all' need, increasing by 2 their intelligence.")
1 ATT CHARISM ALL ALL
gettext("Despite of being extemely hard criticals, these organisms can dissimulate their true nature, being very kind to their audience and informations sources, receiving +1 of Charism.")
1 TEST d100 TENDENCY NEUTRAL
gettext("Impartiality: Before choosing this class, the Journalism student rolls  a d100. If the result is between 1 and 99, he can't be neutral. Else, he can be a Journalism Student of any alingment.")
1 IGNORE PENALTY TESTS SOCIAL
gettext("Journalism students neglects any penalties to their social tests, for being able to survive in turbulent environments.")
0 DIALOG IGNORED NEVER ALL
gettext("As long as the Journalism Student speaks the targets language, he'll never be ignored.")
10
1 CONTACTS
2 ADITIONAL_LANGUAGE
3 INCISIVE_CRITIC
6 WASNT_THAT_WHAT_IVE_SAID
10 DEVIL_TONGUES
11 SARCASTIC_CRITIC
13 ADITIONAL_LANGUAGE
14 SERPENT_TONGUE
19 KNOW_EVERYTHING
20 SHAMEFUL_CRITIC
15
APPRAISE
BLUFF
KNOWLEDGE(ALL)
DIPLOMACY
PROFESSIONAL_SPEECH
DISGUISES
HIDE
SPEAK_LANGUAGE
FURTIVE
INTIMIDATE
OBSERVATE
GET_INFORMATIONS
LISTEN
FREE_PASS
FOOT_ON_MANS_GENITALS
( 5 + INTELLIGENCE )x3
( 5 + INTELLIGENCE )x1
1,0/0/0/0/0/0,0/1/3
2,1/0/0/0/0/0,0/2/4
3,2/0/0/0/0/0,1/2/5
4,3/0/0/0/0/0,1/3/5
5,4/0/0/0/0/0,2/4/5
6,4/0/0/0/0/0,2/5/6
7,5/0/0/0/0/0,2/5/7
8,5/0/0/0/0/0,3/5/8
9,6/1/0/0/0/0,4/5/9
10,7/2/0/0/0/0,4/6/10
11,8/3/0/0/0/0,4/7/11
12,8/3/0/0/0/0,4/8/12
13,9/4/0/0/0/0,5/9/13
14,9/4/0/0/0/0,6/10/14
15,10/5/0/0/0/0,7/11/15
16,11/6/1/0/0/0,8/12/16
17,11/6/1/0/0/0,8/12/17
18,12/7/2/0/0/0,9/13/18
19,12/7/2/0/0/0,9/13/19
20,13/8/3/0/0/0,10/13/20
