gettext("Law Student")
gettext("'- Are we going to the bar taking one?|- Yes, from whose?'|(Typical dialog between two law students)")
gettext("Living  at   the   Campus   disguised  as|penguins,  the Law Students are organisms|that, when perceive the minor possibility|to  make profits  by  some situation they|judge  'juridic',  will  use of all their|verborragy,  deturpations  and sofisms to|make  it.  Is  always important to have a|Law Student in your group (party), be for|avoiding  other  Law  Students  knowledge|(and policial aparate) to take advantages|on  you, or  for taking  advantages  from|others and avoid that iminent punition.")
d6
4
-2 ATT INTELLIGENCE ALL ALL
gettext("For usually  being stupids among anything|that  is  not  related  with  money, they|receive -2 in intelligence.")
-1 ATT CHARISM ALL ALL
gettext("For  their  hungry will to take the  last|copeck of their victims, they  receive -1|in charism.")
2 ATT WISDOM ALL ALL
gettext("By can modify any situation to make money|from it.")
1 SKILL APPRAISE ALL ALL
gettext("Since they know  anything  of  money, the|Law  Student  receives  +1 in Appraise on|their first level.")
4
1 LAWNER_APRENDICE
4 I_AM_WRONG
13 SUPREME_BLUFF
20 FINAL_JUDGE
13
ART_OF_THE_ESCAPE
APPRAISE
BLUFF
COUNTERFEIT
DIPLOMACY
FOOT_ON_MANS_GENITALS
FREE_PASS
GET_INFORMATIONS
INTIMIDATE
KNOWLEDGE(LAW)
KNOWLEDGE_SUFFER
PRESTIDIGITATION
PROFESSIONAL_SPEECH
( 6 + WISDOW )x4
( 6 + WISDOW )x1
1,1/0/0/0/0/0,0/2/0
2,1/0/0/0/0/0,0/3/0
3,2/0/0/0/0/0,1/3/1
4,3/0/0/0/0/0,1/4/1
5,3/0/0/0/0/0,1/4/1
6,4/0/0/0/0/0,2/5/2
7,5/0/0/0/0/0,2/5/2
8,6/1/0/0/0/0,2/6/2
9,6/1/0/0/0/0,3/6/3
10,7/2/0/0/0/0,3/7/3
11,8/3/0/0/0/0,3/7/3
12,9/4/0/0/0/0,4/8/4
13,9/4/0/0/0/0,4/8/4
14,10/5/0/0/0/0,4/9/4
15,11/6/1/0/0/0,5/9/5
16,12/7/2/0/0/0,5/10/5
17,12/7/2/0/0/0,5/10/5
18,13/8/3/0/0/0,5/11/5
19,14/9/4/0/0/0,6/11/5
20,15/10/5/0/0/0,6/12/6
