gettext("Law Student")
gettext("You seem to have more than the average share of intelligence for a man of your background, sneered the lawyer at a witness on the stand.|If I wasn't under oath, I'd return the compliment, replied the witness.")
gettext("Living on Campus disguised as penguins, Law Students are organisms that, when they perceive the minor possibility of making a profit of some situation they judge to be 'juridical', will use all their vocabulary, rhetorical tricks and sophisms to take advantage of it. It is always important to have a Law Student in your group (party), be it to avoid being taken advantage of by the knowledge (and political apparatus) of other Law Students, or to be able to take advantage of others, hence avoiding that looming punishment.")
d6
4
-2 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("Because they are usually quite stupid about anything that isn't related to money, they receive -2 of Intelligence.")
-1 ATTRIBUTE CHARISMA ALL ALL
gettext("Because they are anxious to take the last kopeck from their victims, they receive -1 of Charisma.")
2 ATTRIBUTE WISDOM ALL ALL
gettext("Because they can modify any situation to make money from it, they receive +2 of Wisdom.")
1 SKILL APPRAISE ALL ALL
gettext("Since they know everything about money, the Law Student receives  +1 of Appraise on their first level.")
4
1 LAWNER_APRENDICE
4 I_AM_WRONG
13 SUPREME_BLUFF
20 FINAL_JUDGE
12
ART_OF_THE_ESCAPE
APPRAISE
BLUFF
COUNTERFEIT
DIPLOMACY
FOOT_ON_MANS_GENITALS
FREE_PASS
GET_INFORMATIONS
INTIMIDATE
KNOWLEDGE_SUFFER
PRESTIDIGITATION
PROFESSIONAL_SPEECH
( 6 + WISDOM )x4
( 6 + WISDOM )x1
1,1/0/0/0/0/0,0/2/0
2,1/0/0/0/0/0,0/3/0
3,2/0/0/0/0/0,1/3/1
4,3/0/0/0/0/0,1/4/1
5,3/0/0/0/0/0,1/4/1
6,4/0/0/0/0/0,2/5/2
7,5/0/0/0/0/0,2/5/2
8,6/1/0/0/0/0,2/6/2
9,6/1/0/0/0/0,3/6/3
10,7/2/0/0/0/0,3/7/3
11,8/3/0/0/0/0,3/7/3
12,9/4/0/0/0/0,4/8/4
13,9/4/0/0/0/0,4/8/4
14,10/5/0/0/0/0,4/9/4
15,11/6/1/0/0/0,5/9/5
16,12/7/2/0/0/0,5/10/5
17,12/7/2/0/0/0,5/10/5
18,13/8/3/0/0/0,5/11/5
19,14/9/4/0/0/0,6/11/5
20,15/10/5/0/0/0,6/12/6
