gettext("Mechanical Engineering Student")
gettext("'Today we'll see the comprex prane pracle probrem!'|(Haroldao, Mechanical Teacher)")
gettext("The student of mechanical engineering is the Campus most frustrated person. After enter the graduation on the hope of learn everything about cars, planes,  boats and other mechanical structures of high complexity, they discover that the world is summarized to F = m*a. In possession of that simple equation and of absurd quantities of inexplicable calculations, the teachers of physics make  their life a hell on the basic course. But on specific classes they realize that the world was happy on the basic cycle. Generally they're seen in all classes  inside the Exacts Institute (ICEX), therefore no one is going to finish the graduation regularly.")
d8
4
3 ATT INTELLIGENCE ALL ALL
gettext("Students of Mechanics are going to study crazy, if they want to do something more than hold tight bolts in their lifes, so they receive + 3 of Intelligence.")
3 ATT WISDOM ALL ALL
gettext("Due to the quantity of information about steels, kinds of tempera, tools of plants, electronic systems and other things that they are obliged to swallow, the Students of Mechanics receive +3 of Wisdom.")
-2 ATT STRENGTH
gettext("They receive -2 of Strength, one time that the Autocad mouse doesn't weigh much.")
-10 SOCIAL_TESTS ALL SEX OPPOSITE
gettext("A student of Mechanics always suffers a penalty of -10 in any kind of tests against things of female sex. The total absence of contact with that kind of organism causes a barely unruly frenzy on the student, that should do a test of I Am Not A Fool (with the penalty of -10) to not jump wildily on top of the female. In case of fail, the student enters in frenzy and will try with all his forces to 'copulate' with the same one.")
9
1 CREATE_OBJECTS
2 FOCUS_OPERATE_MECH_OBJ
4 IMPROVED_CREATE_OBJECTS
5 IMPROVED_FOCUS_OP_MECH_OBJ
8 THE_INERTIA_PRINCIPLE
11 BATTLE_CONSTRUCT
14 ACTION_AND_REACTION
17 LIKE_A_CHILD_ON_SLID
20 F=M*A
7
CONDUCTION
DRINKING
KNOWLEDGE(MATERIAL)
OBSERVATE
OPERATE_ELETRONIC_OBJECTS
OPERATE_MECHANIC_OBJECTS
PROFESSIONAL_SPEECH
( 6 + INTELLIGENCE )x3
( 6 + INTELLIGENCE )x1
1,1/0/0/0/0/0,0/1/0
2,1/0/0/0/0/0,1/2/1
3,1/0/0/0/0/0,1/2/1
4,2/0/0/0/0/0,2/3/2
5,2/0/0/0/0/0,2/3/2
6,3/0/0/0/0/0,3/4/3
7,3/0/0/0/0/0,3/4/3
8,4/0/0/0/0/0,4/5/4
9,4/0/0/0/0/0,4/5/4
10,5/0/0/0/0/0,5/6/5
11,5/0/0/0/0/0,5/6/5
12,6/1/0/0/0/0,6/7/6
13,6/1/0/0/0/0,6/7/6
14,7/2/0/0/0/0,7/8/7
15,7/2/0/0/0/0,7/8/7
16,8/3/0/0/0/0,8/9/8
17,8/3/0/0/0/0,8/9/8
18,9/4/0/0/0/0,9/10/9
19,9/4/0/0/0/0,9/10/9
20,10/5/0/0/0/0,10/11/10
