gettext("Mechanical Engineering Student")
gettext("'Today we'll see the comprex prane pracle probrem!'|(Haroldao, Mechanical Teacher)")
gettext("The student of Mechanical Engineering is the most frustrated person on Campus. After choosing that course of studies in hopes of learning everything about cars, planes, boats and other mechanical structures of great complexity, they discover that the world can be summarized to F = m*a. In possession of that simple equation and of absurd quantities of inexplicable calculations, the teachers of physics make their life a hell during the fundamental first year. But in specific classes they realize that the world was happy during that basic cycle. Generally, because they're seen in all classes inside the Exacts Institute (ICEX), it is certain that no one is assured of graduating regularly.")
d8
4
3 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("ME Students will study like crazy, if they want to do something more in their lives than hold bolts while somebody else tightens them, so they receive +3 of Intelligence.")
3 ATTRIBUTE WISDOM ALL ALL
gettext("Due to the quantity of information about steels, kinds of tempera, tools of plants, electronic systems and other things that they are obliged to swallow, the Students of Mechanics receive +3 of Wisdom.")
-2 ATTRIBUTE STRENGTH
gettext("They receive -2 of Strength. After all, the Autocad mouse doesn't weigh much.")
-10 SOCIAL_TESTS ALL SEX OPPOSITE
gettext("A student of Mechanics always suffers a penalty of -10 in any kind of test against things of the female sex. Total absence of contact with that kind of organism causes a barely controlled frenzy in the student, who should do an I Am Not A Fool test (with the penalty of -10) so he won't jump wildly on top of the female. If he fails, the student becomes hysterically frantic and will try as hard as he can to 'copulate' with her.")
9
1 CREATE_OBJECTS
2 FOCUS_OPERATE_MECH_OBJ
4 IMPROVED_CREATE_OBJECTS
5 IMPROVED_FOCUS_OP_MECH_OBJ
8 THE_INERTIA_PRINCIPLE
11 BATTLE_CONSTRUCT
14 ACTION_AND_REACTION
17 LIKE_A_CHILD_ON_SLID
20 F=M*A
6
CONDUCTION
DRINKING
OBSERVATE
OPERATE_ELETRONIC_OBJECTS
OPERATE_MECHANIC_OBJECTS
PROFESSIONAL_SPEECH
( 6 + INTELLIGENCE )x3
( 6 + INTELLIGENCE )x1
1,1/0/0/0/0/0,0/1/0
2,1/0/0/0/0/0,1/2/1
3,1/0/0/0/0/0,1/2/1
4,2/0/0/0/0/0,2/3/2
5,2/0/0/0/0/0,2/3/2
6,3/0/0/0/0/0,3/4/3
7,3/0/0/0/0/0,3/4/3
8,4/0/0/0/0/0,4/5/4
9,4/0/0/0/0/0,4/5/4
10,5/0/0/0/0/0,5/6/5
11,5/0/0/0/0/0,5/6/5
12,6/1/0/0/0/0,6/7/6
13,6/1/0/0/0/0,6/7/6
14,7/2/0/0/0/0,7/8/7
15,7/2/0/0/0/0,7/8/7
16,8/3/0/0/0/0,8/9/8
17,8/3/0/0/0/0,8/9/8
18,9/4/0/0/0/0,9/10/9
19,9/4/0/0/0/0,9/10/9
20,10/5/0/0/0/0,10/11/10
