gettext("Medicine Student")
gettext("'If  I've  tried  Physiotherapy  there, I|should passed  in  first  place  with the|points I've made in Medicine.'|(Mattar, Medician  Student  answering the|provocation   of  Wanucia,  Physiotherapy|Student)")
gettext("The Medicine  Student  is  the thing that|abdicated to their social life  in change|of  an anormal   dedication   to   study,|believing  they'll  be something in life.|Those things haven't any cleverness,  one|time  they  base  their lifes in theories|and more theories.  To  be of this class,|the character need to be submitted to any|hideous  attitude,  like  drown  hookies,|public  peversion,   among   others  that|result in death.")
d6
8
1 ATT STRENGHT ALL ALL
gettext("Although  being  theory  creatures,  they|usually  spent  their  money  in physical|academies, receiving +1 in Strenght.")
2 ATT INTELLIGENCE ALL ALL
gettext("By  the  dedication  to  the  study,  the|Medicine   Student    receive    +2    in|Intelligence.")
-4 ATT WISDOM ALL ALL
gettext("Since  their  attention is only  for  the|books,  these   creatures   haven't   any|cleverness, receiving -4 in Wisdom.")
-3 TESTS NSB ALL ALL
gettext("Frequently in the studies,  the  Medicine|Student  forgot  to  grow up,  being very|susceptible to questions, receiving -3 in|all I am not a Fool (these modifier  fall|to -6 when the target is their father  or|mother).")
4 SKILL BLUFF ALL ALL
gettext("Those creatures receive +4 in  all  Bluff|tests, one time that all bluff they made,|for more ridiculous they are, can  really|(and easily) be true.")
2 SKILL DIPLOMACY RACE BOY
gettext("They Receive +2 in diplomacy when talking|to boys and patys.")
-2 SKILL DIPLOMACY RACE OTHER
gettext("They receive -2 in diplomacy when talking|to other races.")
-4 SKILL DIPLOMACY CLASS FSO
gettext("They receive -4 in Diplomacy when talking|to Physiotherapy Students.")
15
1 EXOTHIC_WEAPON_BISTOURY
1 KNOWLEDGE_SKILLS
1 HIPOCRATES_OATH
2 RAKE
4 PLACED_BLOW
5 DONA_NOBIS_PACEM
5 HEAL_WOUNDS
7 VEINS_AND_ARTERIES
9 HEAL_DISEASES
10 I_AM_STRONG
10 I_AM_STUDY
10 I_AM_SLOW
14 BODY_KNOWLEDGE
16 IMPROVED_BODY_KNOWLEDGE
20 TU_FUI_EGO_IRIS
10
BOHEMIA
BRIBE
CONDUCTION
HEAL
INTIMIDATE
KNOWLEDGE(MEDICINE)
KNOWLEDGE_SUFFER
MEDICAL_LOUD_MOUTH
OUT_OF_TIME
PROFESSIONAL_SPEECH
( 2 + INTELLIGENCE )x3
( 2 + INTELLIGENCE )x1
1,1/0/0/0/0/0,1/0/2
2,1/0/0/0/0/0,2/1/3
3,2/0/0/0/0/0,3/1/4
4,3/0/0/0/0/0,3/2/4
5,4/0/0/0/0/0,4/2/5
6,5/0/0/0/0/0,5/3/5
7,5/0/0/0/0/0,6/4/6
8,6/1/0/0/0/0,6/5/7
9,7/2/0/0/0/0,6/6/8
10,8/3/0/0/0/0,7/7/9
11,9/4/0/0/0/0,8/8/10
12,10/5/0/0/0/0,8/8/11
13,11/6/1/0/0/0,9/8/12
14,12/7/2/0/0/0,10/9/13
15,12/7/2/0/0/0,10/9/14
16,13/8/3/0/0/0,11/9/15
17,13/8/3/0/0/0,11/10/15
18,14/9/4/0/0/0,12/10/16
19,14/9/4/0/0/0,12/10/16
20,15/10/5/0/0/0,26/4/10
