gettext("Medical Student")
gettext("'If I've tried Physiotherapy there, I should passed on first with the points I've made in Medicine.'|(Mattar, Medician Student answering the provocation of Wanucia, Physiotherapy Student)")
gettext("The Medical Student is a person who has given up his social life in exchange for an abnormal dedication to his studies, believing he'll be something in life. Those creatures haven't any cleverness, and base their lives on theories and more theories. To be one of this class, the character needs to be able to behave in a hideous manner: drowning hookies, public perversion, among other activities that result in death.")
d6
8
1 ATTRIBUTE STRENGTH ALL ALL
gettext("Although they are creatures of theory, they usually spend their money in physical academies, receiving +1 of Strength.")
2 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("By the dedication to the studies, the Medicine Student receive +2 of Intelligence.")
-4 ATTRIBUTE WISDOM ALL ALL
gettext("Since their attention is only for the books, these creatures haven't any cleverness, receiving -4 of Wisdom.")
-3 TESTS NSB ALL ALL
gettext("So immersed in his studies is the Medical Student that he has often forgotten to grow up, being very susceptible to questions, receiving -3 on all I am not a Fool tests (diminished to -6 when the target is their father or mother).")
4 SKILL BLUFF ALL ALL
gettext("Those creatures receive +4 on all Bluff tests. They bluff all the time and the more ridiculous their bluffing is, the more easily it can be really true.")
2 SKILL DIPLOMACY RACE BOY
gettext("They Receive +2 of Diplomacy when talking to boys and patys.")
-2 SKILL DIPLOMACY RACE OTHER
gettext("They receive -2 of Diplomacy when talking to other races.")
-4 SKILL DIPLOMACY CLASS FSO
gettext("They receive -4 of Diplomacy when talking to Physiotherapy Students.")
15
1 EXOTHIC_WEAPON_BISTOURY
1 KNOWLEDGE_SKILLS
1 HIPOCRATES_OATH
2 RAKE
4 PLACED_BLOW
5 DONA_NOBIS_PACEM
5 HEAL_WOUNDS
7 VEINS_AND_ARTERIES
9 HEAL_DISEASES
10 I_AM_STRONG
10 I_AM_STUDY
10 I_AM_SLOW
14 BODY_KNOWLEDGE
16 IMPROVED_BODY_KNOWLEDGE
20 TU_FUI_EGO_IRIS
10
BOHEMIA
BRIBE
CONDUCTION
HEAL
INTIMIDATE
KNOWLEDGE_GENERAL
KNOWLEDGE_SUFFER
MEDICAL_LOUD_MOUTH
OUT_OF_TIME
PROFESSIONAL_SPEECH
( 2 + INTELLIGENCE )x3
( 2 + INTELLIGENCE )x1
1,1,1/0/2
2,1,2/1/3
3,2,3/1/4
4,3,3/2/4
5,4,4/2/5
6,5,5/3/5
7,5,6/4/6
8,6,6/5/7
9,7,6/6/8
10,8,7/7/9
11,9,8/8/10
12,10,8/8/11
13,11,9/8/12
14,12,10/9/13
15,12,10/9/14
16,13,11/9/15
17,13,11/10/15
18,14,12/10/16
19,14,12/10/16
20,15,26/4/10
