gettext("Music Student")
gettext("'Without you I sound nothing.'|(Typical commentary of a Lyric-man to a Musician)")
gettext("In a scientific world, few people adventure into different concepts, delving into some art source, like music. The Music Student is a creature with extreme patience, needed to learn all the techniques related to ternary compass atonalisms, has the capacity to create them and a distorted taste for playing one of the most bizarre and occult musical instruments.|Creator's Note: 'Based on the idea that musical tastes are distinct and only the the most open-minded people appreciate distinct rhythms (obviously all that aren't attempts to kill the musical concept), the class was made. So, the same sound, Bach for example, can be beautiful music or terribly boring, depending upon the ear of the listener. Probably a progressive fan will like Bach, but a fan of Tati-Quebra-Barraco, without any musical sense, will think Bach is shit. So, the Music Student will be virtuous and misunderstood.'")
d6
7
-4 ATTRIBUTE STRENGTH ALL ALL
gettext("-4 of Strength because of the fact that their muscles atrophy since they aren't used for anything but playing their instruments.")
-1 ATTRIBUTE CONSTITUTION ALL ALL
gettext("-1 of Constitution for the hours spent in a closed ambient, playing.")
2 ATTRIBUTE DEXTERITY ALL ALL
gettext("+2 of Dexterity for having the ability to play a Gb7M or a Am#5/7/9 on  their strange musical instrument.")
1 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("+1 of Intelligence for knowing those notes, how they are created and all the musical theory envolved on their creation.")
2 ATTRIBUTE CHARISMA ALL ALL
gettext("+2 of Charisma for the capacity to fill people with joy.")
8 ACTION PLAY_INSTRUMENT ALL ALL
gettext("Because of their intense and difficult work since they were children, the Music Students have an incredible capacity to play their bizarre instruments, receiving +8 of bonus when playing them.")
1 RESTRICTION SKILL PLAY_INSTRUMENT ALL
gettext("The Music Student need to have at least one graduation on Play Instrument, of one presented at the Bizarre Musical Instruments List.")
12
1 PLAY_MELODY
1 CALM_MELODY
3 HAPPY_MELODY
5 BATTLE_RYTHIM_MELODY
7 HAMELIN_FLUTTER_MELODY
9 TRANQUILITY_SERENATA
11 ENTERTEINER_CHORDS_MELODY
13 HAMELIN_CHILDREN_MELODY
15 FORTITUDE_MELODY
17 EPIC_CHORDS_MELODY
19 FORBIDDEN_HAMELIN_MELODY
20 PERFECT_HARMONY_MELODY
6
BIZARRE_CLOTHES
BOHEMIA
LISTEN
PERFORMATE
PLAY_INSTRUMENT
PROFESSIONAL_SPEECH
( 3 + INTELLIGENCE )x3
( 3 + INTELLIGENCE )x1
1,1/0/0/0/0/0,0/0/4
2,1/0/0/0/0/0,0/0/5
3,1/0/0/0/0/0,1/1/6
4,1/0/0/0/0/0,2/2/7
5,2/0/0/0/0/0,2/2/8
6,2/0/0/0/0/0,3/3/9
7,2/0/0/0/0/0,4/4/10
8,3/0/0/0/0/0,4/4/11
9,3/0/0/0/0/0,5/5/12
10,4/0/0/0/0/0,5/5/12
11,4/0/0/0/0/0,6/6/13
12,5/0/0/0/0/0,6/6/14
13,5/0/0/0/0/0,7/7/15
14,6/1/0/0/0/0,7/7/15
15,6/1/0/0/0/0,8/8/16
16,7/2/0/0/0/0,8/8/16
17,7/2/0/0/0/0,9/9/17
18,8/3/0/0/0/0,9/9/17
19,9/4/0/0/0/0,10/10/18
20,10/5/0/0/0/0,11/11/19
