gettext("Music Student")
gettext("'Without you I sound nothing.'|(Typical commentary of  a Lyric-man  to a|Musician)")
gettext("In  a  scientific   world,   few   people|adventure in a different  concept, follow|some art source, like  music.  The  Music|Student  is  a  creature   with   extreme|patience to learn all tecnics related  to|ternary  compass  atonalisms,  have   the|capacity to realize them and  a distorced|like to play one of the most bizarre  and|ocult musical instrument.|Note of the Creator: 'Based  on  the idea|that musical likes are distints  and only|the the most understood  ones  appreciate|distinct rhythms (obviously all ones that|aren't  atempts  to   kill,  for bad, the|musical theory), the class was made.  So,|the same sound, Bach for example, can  be|a beautifull music or  something  boring,|depending  from  the  ear   who   listen.|Probably a progressive fan will like Bach|but a fan of Tati-Quebra-Barraco, without|any musical sense, will think  Bach=shit.|So, the Music Student will be a  virtuous|misunderstood.'")
d6
7
-4 ATT STRENGHT ALL ALL
gettext("-4 of  Strenght  by  the fact  that their|muscles atrophy for aren't used more than|the much needed to play their instrument.")
-1 ATT CONSTITUTION ALL ALL
gettext("-1 of Constitution for hours  spent  in a|closed ambient, playing.")
2 ATT DEXTERITY ALL ALL
gettext("+2 of Dexterity for having the ability to|play  a  Gb7M  or  a  Am#5/7/9  on  their|strange musical instrument.")
1 ATT INTELLIGENCE ALL ALL
gettext("+1 of Intelligence for  know those notes,|how  they  are  created  and  all musical|theory envolved on their creation.")
2 ATT CHARISM ALL ALL
gettext("+2 of Charism  for  the  capacity  to joy|people.")
8 ACTION PLAY_INSTRUMENT ALL ALL
gettext("Cause of the extense and hard work  since|they were childs, the Music Student  have|incredible   capacity   to   play   their|bizarre  instrument,  receiving  the   +8|bonus when playing it.")
1 RESTRICTION SKILL PLAY_INSTRUMENT ALL
gettext("The Music Student need to have  at  least|one graduation on Play Instrument, on one|presented  at   the    Bizarre    Musical|Instruments List.")
12
1 PLAY_MELODY
1 CALM_MELODY
3 HAPPY_MELODY
5 BATTLE_RYTHIM_MELODY
7 HAMELIN_FLUTTER_MELODY
9 TRANQUILITY_SERENATA
11 ENTERTEINER_CHORDS_MELODY
13 HAMELIN_CHILDREN_MELODY
15 FORTITUDE_MELODY
17 EPIC_CHORDS_MELODY
19 FORBIDDEN_HAMELIN_MELODY
20 PERFECT_HARMONY_MELODY
7
BIZARRE_CLOTHES
BOHEMIA
KNOWLEDGE(MUSIC)
LISTEN
PERFORMATE
PLAY_INSTRUMENT
PROFESSIONAL_SPEECH
( 3 + INTELLIGENCE )x3
( 3 + INTELLIGENCE )x1
1,1/0/0/0/0/0,0/0/4
2,1/0/0/0/0/0,0/0/5
3,1/0/0/0/0/0,1/1/6
4,1/0/0/0/0/0,2/2/7
5,2/0/0/0/0/0,2/2/8
6,2/0/0/0/0/0,3/3/9
7,2/0/0/0/0/0,4/4/10
8,3/0/0/0/0/0,4/4/11
9,3/0/0/0/0/0,5/5/12
10,4/0/0/0/0/0,5/5/12
11,4/0/0/0/0/0,6/6/13
12,5/0/0/0/0/0,6/6/14
13,5/0/0/0/0/0,7/7/15
14,6/1/0/0/0/0,7/7/15
15,6/1/0/0/0/0,8/8/16
16,7/2/0/0/0/0,8/8/16
17,7/2/0/0/0/0,9/9/17
18,8/3/0/0/0/0,9/9/17
19,9/4/0/0/0/0,10/10/18
20,10/5/0/0/0/0,11/11/19
