gettext("Philosophy Student")
gettext("'Better die by vodka than by boredom!'|(Vladmir Maiakovsky)")
gettext("Not satisfied  with  don't  want  nothing|for their life,  the  Philosophy  Student|enter  the  university   with   just  one|objective:  to   perfect   this   wanting|nothing.  Adepts  of drinking beer and of|to do nothing,  mixing their time between|one and another  activity, the Philosophy|Student become  the  bohemian  master and|full of hot air.")
d6
7
2 ATT CONSTITUTION ALL ALL
gettext("Receive +2 in Constitution, because their|body is barely  of a monk, fully usual to|the alcohol.")
-2 ATT WISDOM ALL ALL
gettext("Since they only study complex things, the|Philosophy  Student  easily  forgets  all|pratical and common things  of the  life,|receiving -2 in Wisdom.")
2 ATT CHARISM ALL ALL
gettext("For spending  almost all  their student's|life  in  pubs,  the  Philosophy  Student|acquire  some  kind  of  aptitude to deal|with others, receiving +2 in Charisma.")
4 SKILL KNOWLEDGE_CLASSIC ALL ALL
gettext("The  Philosophy  Student  receive  +4  in|Knowledge  (classic)  for  the  few  they|study at university.")
4 SKILL BOHEMIA ALL ALL
gettext("Receive +4 in  Bohemia,  cause  they  are|always in Pubs.")
-4 SKILL DEXTERITY ALL ALL
gettext("Receive -4 in all dexterity related tests|one time they are frequently drunk.")
-4 SKILL OUT_OF_TIME ALL ALL
gettext("For don't make any (or very few) classes,|the Philosophy Student receive -4  in Out|of time.")
10
1 DRUNK_FIGHT
1 TURN_TURN_TURN
3 ADITIONAL_FEAT
5 TEMPORARY_GLUCOSE_ADICTION
8 ADITIONAL_FEAT
10 IMPROVED_DRUNK_FIGHT
12 IRON_LIVER
15 CIRRHOSIS_CLOUD
17 ADITIONAL_FEAT
20 SUPREME_DRUNK_FIGHT
8
ART_OF_THE_ESCAPE
BLUFF
BOHEMIA
DRINKING
FURTIVE
HIDE
KNOWLEDGE(CLASSIC)
PROFESSIONAL_SPEECH
( 7 + INTELLIGENCE )x3
( 7 + INTELLIGENCE )x1
1,1/0/0/0/0/0,2/0/1
2,1/0/0/0/0/0,3/1/2
3,1/0/0/0/0/0,4/2/3
4,1/0/0/0/0/0,5/3/4
5,2/0/0/0/0/0,6/4/5
6,2/0/0/0/0/0,7/5/6
7,3/0/0/0/0/0,7/5/6
8,3/0/0/0/0/0,8/6/7
9,4/0/0/0/0/0,9/7/8
10,4/0/0/0/0/0,10/7/8
11,5/0/0/0/0/0,11/8/9
12,5/0/0/0/0/0,11/8/9
13,6/1/0/0/0/0,12/9/10
14,7/2/0/0/0/0,13/10/11
15,7/2/0/0/0/0,14/11/12
16,8/3/0/0/0/0,15/12/13
17,8/3/0/0/0/0,16/13/14
18,9/4/0/0/0/0,17/14/15
19,9/4/0/0/0/0,17/14/15
20,10/5/0/0/0/0,18/15/16
