gettext("Physical Education Student")
gettext("'No! The swimming class is too complex!'|(Typical Physical Education Student thought)")
gettext("Usually taking classes in 'Soccer' and 'Basketball', the dedicated (in the physical sense of the word) Students of Physical Education are things that value muscular force above all. With too many muscles in the brain, those Students possess nothing less than a supernatural resistance in the head - in exchange for some points of Intelligence, really. Finally, these boys are stars on the soccer field but aren't distinguished students of mathematics (hardly knowing the fundamentals of numbers).")
d12
17
3 ATTRIBUTE STRENGTH ALL ALL
gettext("Receive +3 of Strength, due to all those hours spent kicking a ball.")
2 ATTRIBUTE DEXTERITY ALL ALL
gettext("+2 of Dexterity, due to the hours floating in the water.")
4 ATTRIBUTE CONSTITUTION ALL ALL
gettext("+4 of Constitution for hours running in circles.")
-6 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("-6 of Intelligence since they abandoned the books in a remote past.")
-6 ATTRIBUTE WISDOM ALL ALL
gettext("-6 of Wisdom, for the same reason.")
4 SKILL STRENGHT ALL ALL
gettext("The Student of Physical Education receives +4 of Jumping, Climbing, Riding, Swimming, Soccer, Basketball, finally, sports in general or anything that radiates physical power.")
-5 SKILL KNOWLEDGE_GENERAL ALL ALL
gettext("Receive -5 of Knowledge of any sort at all, simply because that they have no idea of the meaning of this word.")
-4 SKILL HIDE ALL ALL
gettext("-4 of Hide, since they are coarse hulks.")
-2 SKILL LISTEN ALL ALL
gettext("-2 of Listen, since their muscles fill their ear canals.")
1 MODIFIER CLASS_ARMATURE ALL ALL
gettext("The Student receives +1 of Natural Armor.")
2 MODIFIER I_AM_NOT_A_FOOL ALL ALL
gettext("Receive +2 of I Am Not A Fool because their brain stops functioning sometimes.")
-4 SKILL TRAIN_ANIMALS ALL ALL
gettext("The Student receives -4 in Training Animals, since, because they haven't absolute control of their muscles, there is a chance of crushing the animal.")
-3 SKILL DRIVER ALL ALL
gettext("Receives -3 in Direction cause they usually get lost among their own muscles.")
-2 SKILL BLUFF ALL ALL
gettext("Also they possess -2 of Bluff, for their muscles practically have a life of their own and easily contradict themselves when they are lying.")
60 RESTRICTION COMBAT CAIR ALL
gettext("By the corpulent size of their muscles and the total absence of control, the Student of Physical  Education  have 0.60 chance to tumble in battle.")
1 RESTRICTION SKILLS INTELIGENCY ALL
gettext("Beyond this, the Student of Physical Education can't buy points on Skills whose ability key is Intelligence.")
99 LIMIT SKILLS SPORTS ALL
gettext("Since extremely limited on its Skills, the Physical Education Student don't have any limit on Sports graduation.")
7
1 IMPROVISE_WEAPONS(BALLS)
3 SHRINK_ITEMS
7 VIRTUALLY_UNDESTRUCTIBLE
10 I_AM_STRONG
13 IMPROVED_IMPROVISE_WEAPONS
15 POWERFULL_ESOPHAGUS
20 ABOMIABLE_MUTATION
1
SPORTS
( 9 + INTELLIGENCE )x3
( 9 + INTELLIGENCE )x1
1,1/0/0/0/0/0,5/0/2
2,2/0/0/0/0/0,6/1/3
3,3/0/0/0/0/0,6/2/4
4,4/0/0/0/0/0,7/3/4
5,5/0/0/0/0/0,7/4/5
6,6/1/0/0/0/0,8/5/6
7,7/2/0/0/0/0,9/5/6
8,8/3/0/0/0/0,10/6/7
9,9/4/0/0/0/0,11/7/8
10,10/5/0/0/0/0,12/7/8
11,11/6/1/0/0/0,13/8/9
12,12/7/2/0/0/0,14/8/9
13,13/8/3/0/0/0,15/14/10
14,14/9/4/0/0/0,15/10/11
15,15/10/5/0/0/0,16/10/12
16,16/11/6/1/0/0,17/11/13
17,17/12/7/2/0/0,18/11/13
18,18/13/8/3/0/0,19/12/14
19,19/14/9/4/0/0,20/12/14
20,30/25/20/15/10/5,30/4/10
