gettext("Physiotherapy Student")
gettext("'You should have studied and  entered the|Federal University!'|(Wanucia, Pysiotherapy Student angry with|Mattar, Medicine Student)")
gettext("Medicine   Students   arqui-rivals,   the|Physiotherapy Student feeds a mortal hate|whith  their   half-blood  brothers.  The|Physiotherapy   Student,  althought  have|something similar with the  Medicine ones|(like elves  and  half-elves),  hate them|with all their forces because  the little|medicians  passed  in the  place that the|physiotherapy   one   always   want.  The|Physiotherapy Student  usually  works  at|physical academies,  to  better  look for|their victims.")
d8
6
1 ATT DEXTERITY ALL ALL
gettext("For hard study  the  human body mobility,|they  can   realize  some   achievements,|receiveing +1 in Dexterity.")
1 ATT INTELLIGENCE ALL ALL
gettext("All  Physiotherapy Student  lost  one  or|more  years  studing  to  be  a  Medicine|Student, receiving +1 in Intelligence.")
-2 ATT WISDOM ALL ALL
gettext("Because of the effort  to  be  a Medicine|Student,    the   little   Physioterapist|inherit the penalty of -2 in Wisdom.")
1 ACTION ATTACK CLASS MED
gettext("Feeding  the  hate  to   their   medicine|rivals, the Physiotherapy Student receive|the  class bonus  against  them, of +1 in|all attacks against Medicians.")
3 SKILL INTELLIGENCE CLASS MED
gettext("They receive +3 in all Listen, Observate,|Bluff  and  I  am not a Fool  tests  when|targeting Medicine Students.")
-5 SOCIAL_TESTS ALL CLASS MED
gettext("Because  they  are  failed medicians, any|chances of social interaction when  there|are Medicine Students in a radius of 20m,|the Physiotherapy Student will receive -5|in all social skills.  If  they fail in a|test  by  5  or  more,  they  will commit|suicide.")
10
1 FAVORITE_PREY_MEDICINE
2 RAKE
4 FAVORITE_PREY_II_MEDICINE
7 INCAPACITATE_BLOW
10 FAVORITE_PREY_III_MEDICINE
13 PROFESSIONAL_PRIDE
15 FAVORITE_PREY_IV_MEDICINE
16 ERROR_INDUCTION
20 FAVORITE_PREY_V_MEDICINE
20 PREY_KNOWLEDGE_MEDICINE
5
DISGUISES
HEAL
KNOWLEDGE(MEDICINE)
MEDICAL_LOUD_MOUTH
PROFESSIONAL_SPEECH
( 3 + INTELLIGENCE )x3
( 3 + INTELLIGENCE )x1
1,1/0/0/0/0/0,1/2/0
2,1/0/0/0/0/0,1/3/1
3,2/0/0/0/0/0,2/4/2
4,3/0/0/0/0/0,2/5/3
5,4/0/0/0/0/0,3/6/4
6,5/0/0/0/0/0,3/7/5
7,5/0/0/0/0/0,4/8/5
8,6/1/0/0/0/0,4/9/5
9,7/2/0/0/0/0,5/10/6
10,8/3/0/0/0/0,6/10/6
11,9/4/0/0/0/0,7/12/6
12,10/5/0/0/0/0,8/13/7
13,11/6/1/0/0/0,9/14/8
14,12/7/2/0/0/0,10/15/8
15,12/7/2/0/0/0,10/15/8
16,13/8/3/0/0/0,12/16/8
17,13/8/3/0/0/0,12/16/9
18,14/9/5/0/0/0,13/17/9
19,14/9/5/0/0/0,13/17/10
20,15/10/5/0/0/0,14/18/10
