gettext("Occupational Therapy Student")
gettext("'- Hey, girls from OT, answer me a question I have since entered the University...|- No, we also don't know to what our graduation is made for and are bored by others asking us about it!'|(Turmalina, Computer Science Student, asking three OT Students)")
gettext("Usually little and fragile, the Occupational Therapy Students can be high emoted watching the most previsible mexican novel. Knowledge by their 'hard'  group therapies, called 'Academic Classes', and for the hours spent painting a little paper like a three years old child (and FOR a three years old child), calling it 'Scientific  Project', the OT Students can't explain to what their graduation is (it's one of the universe's secrets not answered by 42), their life is, their clients, their friends, their bass, the Anamabeka, their..., finally... but sure know what happened at the previous chapter of the midday television novel.")
d4
8
-2 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("Receive -2 of Intelligence, for spent too much time watching TV novels.")
1 ATTRIBUTE WISDOM ALL ALL
gettext("+1 of Wisdom, for the inutiles knowledges obtained watching TV novels.")
3 ATTRIBUTE CHARISM ALL ALL
gettext("+3 of Charism, for not study at the Exacts Sciences Institute (ICEX), usually being pleasants.")
10 SOCIAL_TESTS ALL CLASS ICEX
gettext("For usually have some rare  beauty to the ICEX, the OT Students receive +10 on all social tests against Students from that Institute.")
-12 SKILL FURTIVE CLASS ICEX
gettext("-12 of Furtive when in a radius of 30 meters of at least one ICEX Student.")
-12 SKILL HIDE CLASS ICEX
gettext("-12 of Hide at the same circunstances.")
5 SKILL INTIMIDATE CLASS ICEX
gettext("And +5 of Intimidate for the same reason.")
-4 SKILL OBSERVE ALL ALL
gettext("OT Students have the tendency to play that musical instrument someone call bass, receiving -4 of Observe.")
6
1 GROUP_THERAPY_I
3 CROCODILE_TEARS
6 GROUP_THERAPY_II
12 GROUP_THERAPY_III
14 ICEX_SHOCK
20 SUPREME_GROUP_THERAPY
9
BLUFF
BOHEMIA
DIPLOMACY
GET_INFORMATIONS
MEDICAL_LOUD_MOUTH
KNOWLEDGE(THERAPY)
PLAY_INSTRUMENT
PROFESSIONAL_SPEECH
SEE_LIES
( 5 + CHARISM )x3
( 2 + CHARISM )x2
1,1/0/0/0/0/0,0/0/2
2,1/0/0/0/0/0,0/0/2
3,1/0/0/0/0/0,1/1/3
4,1/0/0/0/0/0,2/2/3
5,2/0/0/0/0/0,2/2/4
6,2/0/0/0/0/0,3/3/4
7,2/0/0/0/0/0,3/3/5
8,3/0/0/0/0/0,4/4/5
9,3/0/0/0/0/0,4/4/6
10,4/0/0/0/0/0,4/4/6
11,4/0/0/0/0/0,5/5/7
12,5/0/0/0/0/0,5/5/7
13,5/0/0/0/0/0,6/6/8
14,6/1/0/0/0/0,6/6/9
15,6/1/0/0/0/0,7/7/10
16,7/2/0/0/0/0,7/7/11
17,7/2/0/0/0/0,8/8/12
18,7/2/0/0/0/0,8/8/13
19,8/3/0/0/0/0,9/9/14
20,8/3/0/0/0/0,9/9/15
