gettext("Occupational Therapy Student")
gettext("'Hey, girls from OT, there's a question I've had in my mind since I entered the University. Can you answer it for me?...| No, we don't know what our diploma will allow us to do and we're bored by others asking us about it!'|(Turmalina, Computer Science Student, interviewing three OT Students)")
gettext("Usually little and fragile, the Occupational Therapy Students can become highly emotional when they watch Mexican soap operas, however conventional. Known for their 'hard' group therapies, called 'Academic Classes', and for the hours they spend painting a little piece of paper like a three-year-old child (and FOR a three-year-old child), calling it a 'Scientific Project', the OT Students can't explain the purpose of their diploma (it's one of the universe's secrets not answered by 42), of their lives, their clients, their friends, their bass guitars, the Anamabeka, their..., finally... But they sure do know what happened in the previous chapter of the midday television soap opera.")
d4
8
-2 ATTRIBUTE INTELLIGENCE ALL ALL
gettext("Receive -2 of Intelligence, for spending too much time watching soap operas on TV.")
1 ATTRIBUTE WISDOM ALL ALL
gettext("+1 of Wisdom, for the inutiles knowledges obtained watching TV novels.")
3 ATTRIBUTE CHARISMA ALL ALL
gettext("+3 of Charisma, for not studying at the Exact Sciences Institute (ICEX), and for usually being very nice.")
10 SOCIAL_TESTS ALL CLASS ICEX
gettext("Because they symbolize rare beauty to the Students of the ISEX,  the OT Students receive +10 on all social tests against Students from that Institute.")
-12 SKILL FURTIVE CLASS ICEX
gettext("-12 of Furtive when in a radius of 30 meters of at least one ICEX Student.")
-12 SKILL HIDE CLASS ICEX
gettext("-12 of Hide in the same circunstances.")
5 SKILL INTIMIDATE CLASS ICEX
gettext("And +5 of Intimidate for the same reason.")
-4 SKILL OBSERVE ALL ALL
gettext("OT Students have a tendency to play that musical instrument called a bass, receiving -4 of Observe.")
6
1 GROUP_THERAPY_I
3 CROCODILE_TEARS
6 GROUP_THERAPY_II
12 GROUP_THERAPY_III
14 ICEX_SHOCK
20 SUPREME_GROUP_THERAPY
9
BLUFF
BOHEMIA
DIPLOMACY
GET_INFORMATIONS
MEDICAL_LOUD_MOUTH
KNOWLEDGE_GENERAL
PLAY_INSTRUMENT
PROFESSIONAL_SPEECH
SEE_LIES
( 5 + CHARISMA )x3
( 2 + CHARISMA )x2
1,1,0/0/2
2,1,0/0/2
3,1,1/1/3
4,1,2/2/3
5,2,2/2/4
6,2,3/3/4
7,2,3/3/5
8,3,4/4/5
9,3,4/4/6
10,4,4/4/6
11,4,5/5/7
12,5,5/5/7
13,5,6/6/8
14,6,6/6/9
15,6,7/7/10
16,7,7/7/11
17,7,8/8/12
18,7,8/8/13
19,8,9/9/14
20,8,9/9/15
